### ISSUE TITLE
Bug: 4th Problem Saving Issues on Problem Edit

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1620]
Bug: the EdReady SME has reported a bug regarding the saving of a fourth problem when editing the problem set. 

EdReady Video of Bug Occurring: https://www.loom.com/share/9ccbd97a93a24f908f3a33e1880c6cb2

I have not yet been able to replicate this bug.

**Comment by johnhbenetech** [comment]
@bognasoldev89 you can disregard as I was able to reproduce it. 

@alexrcabral @rupeshparab 
I believe it may be related to the content being very large, related error is below. So it's basically the pasted problem prompt is over character limit (255). the "4th problem" thing is a red herring

So @alexrcabral i think the options are either:
* Increase the length limit of the description in the database (or remove it entirely)
* Add front end validation that either halts entry at the character limit or does the twitter thing where it tells you how many characters you have to remove.


```
2021-01-04 18:15:21.755 ERROR 15 --- [nio-8081-exec-1] o.h.e.j.s.SqlExceptionHelper             : ERROR: value too long for type character varying(255)
2021-01-04 18:15:21.755 ERROR 15 --- [nio-8081-exec-1] o.h.e.j.s.SqlExceptionHelper : ERROR: value too long for type character varying(255)
2021-01-04T12:15:21.768-06:00	2021-01-04 18:15:21.764 ERROR 15 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement] with root cause
2021-01-04T12:15:21.768-06:00	org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
2021-01-04T12:15:21.768-06:00	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar!/:42.2.2]
2021-01-04T12:15:21.768-06:00	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar!/:42.2.2]
2021-01-04T12:15:21.768-06:00	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar!/:42.2.2]
2021-01-04T12:15:21.768-06:00	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar!/:42.2.2]
2021-01-04T12:15:21.768-06:00	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar!/:42.2.2]
2021-01-04T12:15:21.768-06:00	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155) ~[postgresql-42.2.2.jar!/:42.2.2]
```

**Comment by alexrcabral** [comment]
Thanks @johnhbenetech! Good to know that the issue is stemming from the character limit. 

Those are good suggestions -- I think a combination of the two would address it well: 
- The character length should be increased to 2,000 characters
- Front end validation should be added to halt entry after 2,000 characters is reached

**Comment by johnhbenetech** [comment]
@alexrcabral I moved to backlog, can you make sure priority is right

**Comment by alexrcabral** [comment]
Great, thanks @johnhbenetech! I've updated its priority so the backlog should be in order now

**Comment by rupeshparab** [comment]
this issue should be fixed on QA now

**Comment by abaranowska1** [comment]
**Tested**
Confirmed that I can create a problem set where the prompt is over 255 characters I tried with 300,1000,2000 and more ( all copied ) and all work fine for me, but I think that when we have a longer prompt we should wrap the text because it will be more readable. @alexrcabral What do you think?
![Peek 2021-01-14 15-41](https://user-images.githubusercontent.com/61964176/104606504-1ac73e80-5680-11eb-85a6-b2c63073f700.gif)

**Comment by alexrcabral** [comment]
Thanks @abaranowska1 -- it looks like it's overflowing properly when there are breaks between words, but a single long word with many many characters is breaking it. It would be good to allow for overflow when spaces aren't available. 

<img width="1142" alt="Screen Shot 2021-01-14 at 5 28 40 PM" src="https://user-images.githubusercontent.com/47576069/104668946-f4a89b00-568d-11eb-9373-1042919de4dd.png">

Currently it's not halting entry after 2,000 characters is reached. It allows for entry of greater than 2,000 characters, then throws an error if you click "Add Problem".

<img width="371" alt="Screen Shot 2021-01-14 at 5 29 43 PM" src="https://user-images.githubusercontent.com/47576069/104669038-1dc92b80-568e-11eb-83b5-425184a1e652.png">

Next Steps: 
- Halting entry after 2,000 characters should be fixed (to clarify, this should prevent from entering further text, allow for backspacing) 
- Allow for overflow between characters in a single word lacking spaces, when there are 1) no spaces in a given line, and 2) it would otherwise exceed the horizontal space on the web page

**Comment by rupeshparab** [comment]
Added both the fixes
